"use client";

import {
	Link,
	useLocation,
	useNavigate,
	useRouter,
} from "@tanstack/react-router";
import { ArrowRight, FileText } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { syncPaymentStatus } from "@/app/actions/payment";
import { CreditExhaustedModal } from "@/components/chat/credit-exhausted-modal";
import { TableOfContents } from "@/components/prd/table-of-contents";
import { usePanelResize } from "@/hooks/use-panel-resize";
import { GUARD_WAIT_MS } from "@/lib/constants";
import {
	consumeResumeIntent,
	consumeSuppressAutoGen,
} from "@/lib/prompt-handoff";
import { readSseStream } from "@/lib/sse-stream";
import { cn } from "@/lib/utils";
import { useChatStore, useUIStore } from "@/store";
import type { Plan } from "@/types/database";
import { AcViewer } from "./ac-viewer";

interface AcDetailProps {
	projectId: string;
	projectName: string;
	latestAcContent?: string | null;
	latestPrdContent?: string;
	plan?: Plan;
	acStatus?: string | null;
}

// ponytail: module-level in-flight guard. StrictMode's phantom
// unmount->remount aborts the first fetch but the remount fires a second
// generate before the server frees its claim — dedupe at module scope so both
// mounts share one generation per project instead of racing two. Keyed by the
// owning controller so an older request's cleanup can never release a guard
// that a newer request has since acquired.
const inFlightAcProjects = new Map<string, AbortController>();

/** Release the guard only when this request still owns it. */
function releaseAcGuard(projectId: string, owner: AbortController) {
	if (inFlightAcProjects.get(projectId) === owner) {
		inFlightAcProjects.delete(projectId);
	}
}

export function AcDetail({
	projectId,
	projectName,
	latestAcContent,
	latestPrdContent,
	plan = "free",
	acStatus,
}: AcDetailProps) {
	const router = useRouter();
	const navigate = useNavigate();
	const searchStr = useLocation({ select: (l) => l.searchStr });
	const showToast = useUIStore((s) => s.showToast);
	const setGeneratingAC = useChatStore((s) => s.setGeneratingAC);
	const creditsExhausted = useChatStore((s) => s.creditsExhausted);
	const setCreditsExhausted = useChatStore((s) => s.setCreditsExhausted);
	const { leftWidth, onStartDragLeft, isDraggingLeft } = usePanelResize();

	const [isGenerating, setIsGenerating] = useState(false);
	const [paywallOpen, setPaywallOpen] = useState(false);
	const [streamingContent, setStreamingContent] = useState<string>("");
	const [thinkingText, setThinkingText] = useState("");
	const [hasError, setHasError] = useState(false);
	const [saveFailed, setSaveFailed] = useState(false);
	const [isRetrySaving, setIsRetrySaving] = useState(false);
	const [localAcContent, setLocalAcContent] = useState<string | null>(
		latestAcContent || null,
	);
	const hasAutoGenerated = useRef(false);
	const abortRef = useRef<AbortController | null>(null);
	const contentRef = useRef("");

	// Sync loader latestAcContent to local optimistic state.
	// Keep optimistic content (contentRef.current) during invalidate gap so
	// post-done doesn't flash the empty placeholder.
	useEffect(() => {
		if (latestAcContent) {
			setLocalAcContent(latestAcContent);
		} else if (!contentRef.current) {
			setLocalAcContent(null);
		}
	}, [latestAcContent]);

	const acContent = localAcContent;

	const handleRetrySave = useCallback(async () => {
		setIsRetrySaving(true);
		try {
			const response = await fetch("/api/ac/save", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ projectId, content: contentRef.current }),
			});
			const data = await response.json();
			if (!response.ok) throw new Error(data.error || "Gagal menyimpan AC");
			setSaveFailed(false);
			setHasError(false);
			router.invalidate();
			showToast("AC berhasil disimpan!", "success");
		} catch (error: unknown) {
			showToast(
				error instanceof Error ? error.message : "Gagal menyimpan AC",
				"error",
			);
		} finally {
			setIsRetrySaving(false);
		}
	}, [projectId, showToast, router]);

	const handleGenerate = useCallback(async () => {
		if (!latestPrdContent) {
			showToast("PRD belum tersedia. Generate PRD terlebih dahulu.", "error");
			return;
		}
		// StrictMode remount fires while the phantom attempt is still settling
		// (its abort lands within ms). Wait briefly for the guard to free up so
		// the real retry proceeds; a genuine duplicate (double-click) times out
		// silently instead of stacking a second request.
		if (inFlightAcProjects.has(projectId)) {
			const deadline = Date.now() + GUARD_WAIT_MS;
			while (inFlightAcProjects.has(projectId) && Date.now() < deadline) {
				await new Promise((r) => setTimeout(r, 50));
			}
			if (inFlightAcProjects.has(projectId)) return;
		}

		abortRef.current?.abort();
		const controller = new AbortController();
		abortRef.current = controller;
		// Acquire the guard keyed by this controller — only this request can
		// release it, so an aborted older stream can't free a newer one's slot.
		inFlightAcProjects.set(projectId, controller);
		setIsGenerating(true);
		setGeneratingAC(true);
		setStreamingContent("");
		contentRef.current = "";
		setHasError(false);
		setSaveFailed(false);

		try {
			const response = await fetch("/api/ac/generate", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					projectId,
				}),
				signal: controller.signal,
			});
			if (!response.ok) {
				const error = await response.json().catch(() => ({}));
				if (response.status === 403) {
					if (error.code === "UPGRADE_REQUIRED") {
						showToast(
							"Generate AC hanya tersedia di paket Pro dan Hengker.",
							"error",
						);
					} else {
						setCreditsExhausted({
							stage: "ac",
							message: error.error || "Kredit habis.",
						});
					}
					setIsGenerating(false);
					setGeneratingAC(false);
					return;
				}
				if (response.status === 409) {
					// Release our own guard slot (we own it), then check whether
					// any *other* live request still owns a generation. Owner
					// alive (double-click) → stay silent, their UI is streaming.
					// No owner (StrictMode phantom aborted it) → the claim was
					// stale; paint the retryable error state instead of a
					// fake-loading dead end.
					releaseAcGuard(projectId, controller);
					if (!inFlightAcProjects.has(projectId)) {
						setHasError(true);
						showToast(
							"Sesi generate sebelumnya terputus. Klik Coba Lagi.",
							"error",
						);
					}
					setIsGenerating(false);
					setGeneratingAC(false);
					return;
				}
				throw new Error(error.error || "Failed to generate AC");
			}
			let receivedTerminalEvent = false;
			// The shared parser flushes the trailing buffer so a final done/error
			// frame without a newline is never dropped, and stops the moment a
			// terminal event arrives so nothing after it can overwrite the result.
			for await (const data of readSseStream(response.body)) {
				let event: { type?: string; content?: string; error?: string };
				try {
					event = JSON.parse(data);
				} catch {
					continue;
				}
				if (event.type === "thinking") {
					setThinkingText((prev) => prev + (event.content ?? ""));
				} else if (event.type === "delta") {
					// Clear unconditionally — reading the stale render-time
					// `thinkingText` here left the panel visible after the first
					// token arrived. React bails out when already empty.
					setThinkingText("");
					contentRef.current += event.content ?? "";
					setStreamingContent((prev) => prev + (event.content ?? ""));
				} else if (event.type === "done") {
					receivedTerminalEvent = true;
					// Optimistic: tampilkan streamingContent langsung tanpa nunggu loader
					setLocalAcContent(contentRef.current);
					router.invalidate();
					showToast("Acceptance Criteria berhasil digenerate!", "success");
					setIsGenerating(false);
					setGeneratingAC(false);
					break;
				} else if (event.type === "error") {
					receivedTerminalEvent = true;
					setIsGenerating(false);
					setGeneratingAC(false);
					// Content already streamed but the DB save (Phase 2) failed - offer
					// recovery instead of the generic error state (PRD US-2, AC-2.1/2.2).
					if (contentRef.current.length > 0) {
						setSaveFailed(true);
					} else {
						setHasError(true);
					}
					showToast(event.error || "Gagal generate AC", "error");
					break;
				}
			}
			// Stream closed without a done/error event (connection dropped mid-stream) -
			// content is silently truncated, so surface it instead of leaving no signal.
			if (!receivedTerminalEvent) {
				if (contentRef.current.length > 0) setSaveFailed(true);
				else setHasError(true);
			}
			setIsGenerating(false);
			setGeneratingAC(false);
		} catch (error: unknown) {
			const isAbort =
				(error instanceof DOMException || error instanceof Error) &&
				error.name === "AbortError";
			if (isAbort) {
				// A newer handleGenerate call already superseded this one (see
				// abortRef.current?.abort() above), or unmount cleared the ref.
				// Either way that flow owns isGenerating/error state now.
				if (abortRef.current !== controller) {
					// Abort came from unmount/route transition, not a newer
					// handleGenerate taking over (abortRef was cleared). Surface a
					// retryable error so the user isn't left at a dead-end - without
					// the misleading "timeout" toast this path used to show.
					if (abortRef.current === null) {
						setHasError(true);
						setIsGenerating(false);
						setGeneratingAC(false);
					}
					return;
				}
				showToast(
					"Generate AC dibatalkan (timeout). Klik Generate ulang.",
					"error",
				);
				setHasError(true);
				setIsGenerating(false);
				setGeneratingAC(false);
				return;
			}
			console.error("Generate AC error:", error);
			const msg = error instanceof Error ? error.message : "Gagal generate AC";
			showToast(msg, "error");
			setHasError(true);
			setIsGenerating(false);
			setGeneratingAC(false);
		} finally {
			releaseAcGuard(projectId, controller);
		}
	}, [
		projectId,
		latestPrdContent,
		showToast,
		router,
		setGeneratingAC,
		setCreditsExhausted,
	]);

	// Sync server acStatus into store so navbar "Generate Task" stays disabled on refresh (Zustand is in-memory only)
	useEffect(() => {
		setGeneratingAC(acStatus === "generating");
	}, [acStatus, setGeneratingAC]);

	// Auto-generate AC on first visit
	useEffect(() => {
		if (plan === "free") return; // jangan auto-generate, tampilkan paywall
		if (
			!latestPrdContent ||
			latestAcContent ||
			hasAutoGenerated.current ||
			isGenerating
		)
			return;
		// Suppress auto-generate when navigating from History (user must click explicitly)
		if (consumeSuppressAutoGen(projectId)) return;
		hasAutoGenerated.current = true;
		handleGenerate();
		// ponytail: auto-gen once per mount; ref guard prevents re-run when handleGenerate ref changes
	}, [
		latestPrdContent,
		latestAcContent,
		handleGenerate,
		projectId,
		isGenerating,
		plan,
	]);

	// Auto-resume AC generation after payment return.
	// Keyed by the raw search string + a per-orderId guard: `new
	// URLSearchParams(searchStr)` is a fresh object every render, and
	// handleGenerate changes identity mid-generation, so without this the
	// resume flow could fire duplicate sync/generate calls while the
	// Midtrans query params are still in the URL.
	const resumedAcPaymentsRef = useRef<Set<string>>(new Set());
	useEffect(() => {
		const params = new URLSearchParams(searchStr);
		const orderId = params.get("order_id");
		const payment = params.get("payment");
		if (!orderId || payment !== "success") return;
		if (resumedAcPaymentsRef.current.has(orderId)) return;
		resumedAcPaymentsRef.current.add(orderId);
		(async () => {
			try {
				const res = await syncPaymentStatus({ data: orderId });
				if (!res.success) return;
				const resumedStage = consumeResumeIntent(projectId);
				if (resumedStage === "ac") {
					hasAutoGenerated.current = true;
					handleGenerate();
				}
				// Strip Midtrans query params via TanStack Router to keep history in sync
				navigate({ to: ".", search: {}, replace: true });
			} catch (e) {
				console.error("Auto-resume payment sync failed:", e);
			}
		})();
	}, [searchStr, handleGenerate, navigate, projectId]);

	// Abort in-flight generation on unmount/project switch only - kept as a
	// separate effect (not the trigger effect's cleanup). Also resets
	// hasAutoGenerated so StrictMode's dev-mode phantom unmount->remount cycle
	// retries the aborted fetch instead of leaving it dead (the ref survives
	// the phantom cycle and would otherwise permanently block the retry).
	// biome-ignore lint/correctness/useExhaustiveDependencies: projectId triggers cleanup on project switch
	useEffect(() => {
		return () => {
			abortRef.current?.abort();
			// Clear the ref so the aborted call's catch can tell an unmount abort
			// (ref === null) from a superseded one (ref points at a newer call) -
			// mirroring task-detail.tsx. Also frees the module guard instantly
			// instead of after the rejection settles.
			abortRef.current = null;
			hasAutoGenerated.current = false;
			setGeneratingAC(false);
			// Project switch may reuse this component instance - clear stale save-failure
			// state so a recovery banner/content from the previous project can't leak in.
			setSaveFailed(false);
			setHasError(false);
			setStreamingContent("");
			setLocalAcContent(null);
			contentRef.current = "";
		};
	}, [projectId, setGeneratingAC]);

	if (!latestPrdContent) {
		return (
			<div className="flex h-dvh items-center justify-center bg-onyx text-(--text-primary)">
				<div className="text-center">
					<FileText
						size={64}
						className="mx-auto mb-4 text-(--text-secondary)"
					/>
					<h2 className="mb-2 text-xl font-[510] text-(--text-primary)">
						PRD Belum Tersedia
					</h2>
					<p className="mb-6 text-(--text-secondary)">
						Generate PRD terlebih dahulu sebelum membuat Acceptance Criteria.
					</p>
					<Link
						to="/prd/$id"
						params={{ id: projectId }}
						className="btn-primary inline-flex items-center gap-2 rounded-md px-4 py-2"
					>
						<ArrowRight size={16} /> Ke PRD
					</Link>
				</div>
			</div>
		);
	}

	const isStreaming = isGenerating;

	return (
		<>
			<div className="flex h-dvh flex-col overflow-hidden bg-onyx text-(--text-primary)">
				<div className="flex flex-1 overflow-hidden">
					{/* Left: TOC — width/handle live on this wrapper: the aside below
				    scrolls (overflow-y-auto), and a scrolling ancestor clips
				    absolutely positioned children at its padding edge, which
				    shifts the resize hitbox left of the divider. */}
					<div
						style={{ width: `${leftWidth}px`, background: "var(--bg-page)" }}
						className={cn(
							"relative hidden h-full shrink-0 md:block",
							!isDraggingLeft && "transition-[width] duration-300",
						)}
					>
						<aside className="h-full w-full overflow-y-auto overflow-x-hidden border-r border-(--color-graphite) bg-onyx p-4">
							{isStreaming && !streamingContent ? (
								<div className="space-y-2.5">
									{[1, 2, 3, 4, 5, 6].map((i) => (
										<div
											key={i}
											className="h-3.5 rounded bg-steel/60 animate-pulse"
											style={{ width: `${55 + (i % 3) * 15}%` }}
										/>
									))}
								</div>
							) : (
								<TableOfContents
									content={isStreaming ? streamingContent : acContent || ""}
									maxLevel={2}
								/>
							)}
						</aside>
						<div
							aria-hidden="true"
							className="absolute right-[-4px] top-0 z-10 h-full w-2 cursor-col-resize transition-colors hover:bg-indigo/20"
							onMouseDown={onStartDragLeft}
						/>
					</div>

					{/* Center Document View */}
					<div
						className={cn("flex min-w-0 flex-1 flex-col overflow-hidden")}
						style={{ background: "var(--bg-page)" }}
					>
						{/* Topbar */}
						<div className="flex shrink-0 items-center border-b border-(--color-graphite) bg-obsidian px-4 py-3">
							<h1 className="truncate font-(--font-inter) text-lg font-[510] text-(--text-primary)">
								AC - {projectName}
							</h1>
						</div>

						{saveFailed && (
							<div
								role="alert"
								className="flex shrink-0 flex-wrap items-center gap-3 border-b border-(--color-graphite) bg-amber-500/10 px-4 py-3 text-sm"
							>
								<span className="text-amber-500">
									AC berhasil digenerate tetapi gagal disimpan karena masalah
									koneksi database.
								</span>
								<button
									type="button"
									onClick={handleRetrySave}
									disabled={isRetrySaving}
									className="rounded-md bg-amber-500 px-3 py-1.5 font-[510] text-black transition-opacity hover:opacity-90 disabled:opacity-50"
								>
									{isRetrySaving ? "Menyimpan..." : "Retry Simpan (Tanpa AI)"}
								</button>
								<button
									type="button"
									onClick={handleGenerate}
									disabled={isRetrySaving}
									className="rounded-md border border-(--color-graphite) px-3 py-1.5 text-(--text-secondary) transition-colors hover:bg-white/5 disabled:opacity-50"
								>
									Generate Ulang
								</button>
							</div>
						)}

						{plan === "free" && !acContent && !isGenerating && (
							<div className="shrink-0 border-t border-graphite px-4 py-3">
								<div className="flex flex-wrap items-center justify-between gap-3">
									<p className="text-sm text-fog">
										Generate Acceptance Criteria hanya untuk paket Pro/Hengker.
									</p>
									<button
										type="button"
										onClick={() => setPaywallOpen(true)}
										className="btn-primary flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-[510] transition-all hover:brightness-105 active:scale-[0.98]"
									>
										<span className="whitespace-nowrap">Upgrade ke Pro</span>
										<ArrowRight size={12} />
									</button>
								</div>
							</div>
						)}
						{/* AC Viewer */}
						<div className="flex-1 overflow-hidden">
							{isGenerating && thinkingText && !streamingContent && (
								<details className="text-xs text-fog/60 mb-2 px-4" open>
									<summary className="cursor-pointer select-none">
										AI sedang berpikir...
									</summary>
									<pre className="mt-1 whitespace-pre-wrap text-xs text-fog/40 max-h-40 overflow-y-auto custom-scrollbar">
										{thinkingText}
									</pre>
								</details>
							)}
							<AcViewer
								content={acContent}
								streamingContent={streamingContent}
								isStreaming={isStreaming}
								hasError={hasError}
								thinkingText={thinkingText}
								onGenerate={handleGenerate}
								projectName={projectName}
								plan={plan}
								className=""
							/>
						</div>
					</div>
				</div>
			</div>

			<CreditExhaustedModal
				isOpen={creditsExhausted?.stage === "ac" || paywallOpen}
				onClose={() => {
					setCreditsExhausted(null);
					setPaywallOpen(false);
				}}
				errorMessage={
					paywallOpen && creditsExhausted?.stage !== "ac"
						? "Upgrade ke Pro untuk generate Acceptance Criteria dan lanjut ke tahap berikutnya."
						: creditsExhausted?.message || ""
				}
				title={
					paywallOpen && creditsExhausted?.stage !== "ac"
						? "Lanjut ke AC butuh Pro"
						: undefined
				}
				projectId={projectId}
				stage="ac"
				currentPlan={plan}
			/>
		</>
	);
}
