/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AcIdRouteImport } from './routes/ac/$id'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiReportErrorRouteImport } from './routes/api/report-error'
import { Route as AskIdRouteImport } from './routes/ask/$id'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CodebaseIdRouteImport } from './routes/codebase/$id'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as KanbanIdRouteImport } from './routes/kanban/$id'
import { Route as PrdIdRouteImport } from './routes/prd/$id'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsFeedbackRouteImport } from './routes/settings/feedback'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as TaskIdRouteImport } from './routes/task/$id'
import { Route as ApiAcGenerateRouteImport } from './routes/api/ac/generate'
import { Route as ApiAcSaveRouteImport } from './routes/api/ac/save'
import { Route as ApiAskOptionsRouteImport } from './routes/api/ask/options'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronBillingRouteImport } from './routes/api/cron/billing'
import { Route as ApiExportPrdRouteImport } from './routes/api/export/prd'
import { Route as ApiExportZipRouteImport } from './routes/api/export/zip'
import { Route as ApiKanbanPidRouteImport } from './routes/api/kanban/$pid'
import { Route as ApiKanbanStreamRouteImport } from './routes/api/kanban/stream'
import { Route as ApiKanbanUpdateStatusRouteImport } from './routes/api/kanban/update-status'
import { Route as ApiPaymentsCreateRouteImport } from './routes/api/payments/create'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiProjectsIndexRouteImport } from './routes/api/projects/index'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'
import { Route as ApiTaskProjectIdRouteImport } from './routes/api/task/$projectId'
import { Route as ApiTaskGenerateRouteImport } from './routes/api/task/generate'
import { Route as ApiUserPlanRouteImport } from './routes/api/user/plan'
import { Route as PrdShareTokenRouteImport } from './routes/prd/share/$token'
import { Route as ApiCodebaseProjectIdSessionRouteImport } from './routes/api/codebase/$projectId/session'
import { Route as ApiCodebaseProjectIdStatusRouteImport } from './routes/api/codebase/$projectId/status'
import { Route as ApiProjectsIdLastRouteRouteImport } from './routes/api/projects/$id/last-route'
import { Route as ApiProjectsIdResetProgressRouteImport } from './routes/api/projects/$id/reset-progress'
import { Route as ApiProjectsIdStepRouteImport } from './routes/api/projects/$id/step'
import { Route as ApiProjectsIdVersionsRouteImport } from './routes/api/projects/$id/versions'
import { Route as ApiSettingsApiKeysIndexRouteImport } from './routes/api/settings/api-keys/index'
import { Route as ApiSettingsApiKeysIdRouteImport } from './routes/api/settings/api-keys/$id'
import { Route as ApiSettingsApiKeysAutoRouteImport } from './routes/api/settings/api-keys/auto'
import { Route as ApiV1ProjectsIdRouteImport } from './routes/api/v1/projects/$id'
import { Route as ApiV1ProjectsIdAcRouteImport } from './routes/api/v1/projects/$id/ac'
import { Route as ApiV1ProjectsIdKanbanRouteImport } from './routes/api/v1/projects/$id/kanban'
import { Route as ApiV1ProjectsIdPrdRouteImport } from './routes/api/v1/projects/$id/prd'
import { Route as ApiV1ProjectsIdTasksRouteImport } from './routes/api/v1/projects/$id/tasks'
import { Route as ApiV1SubtasksIdStatusRouteImport } from './routes/api/v1/subtasks/$id/status'
import { Route as ApiV1TasksIdStatusRouteImport } from './routes/api/v1/tasks/$id/status'
import { Route as ApiV1ProjectsIdCodebaseAnalysisRouteImport } from './routes/api/v1/projects/$id/codebase/analysis'
import { Route as ApiV1ProjectsIdCodebaseCompleteRouteImport } from './routes/api/v1/projects/$id/codebase/complete'
import { Route as ApiV1ProjectsIdCodebaseFilesRouteImport } from './routes/api/v1/projects/$id/codebase/files'
import { Route as ApiV1ProjectsIdCodebaseManifestRouteImport } from './routes/api/v1/projects/$id/codebase/manifest'
import { Route as ApiV1ProjectsIdCodebaseSyncRouteImport } from './routes/api/v1/projects/$id/codebase/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcIdRoute = AcIdRouteImport.update({
  id: '/ac/$id',
  path: '/ac/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportErrorRoute = ApiReportErrorRouteImport.update({
  id: '/api/report-error',
  path: '/api/report-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIdRoute = AskIdRouteImport.update({
  id: '/ask/$id',
  path: '/ask/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseIdRoute = CodebaseIdRouteImport.update({
  id: '/codebase/$id',
  path: '/codebase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanIdRoute = KanbanIdRouteImport.update({
  id: '/kanban/$id',
  path: '/kanban/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdIdRoute = PrdIdRouteImport.update({
  id: '/prd/$id',
  path: '/prd/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFeedbackRoute = SettingsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const TaskIdRoute = TaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcGenerateRoute = ApiAcGenerateRouteImport.update({
  id: '/api/ac/generate',
  path: '/api/ac/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcSaveRoute = ApiAcSaveRouteImport.update({
  id: '/api/ac/save',
  path: '/api/ac/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskOptionsRoute = ApiAskOptionsRouteImport.update({
  id: '/api/ask/options',
  path: '/api/ask/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBillingRoute = ApiCronBillingRouteImport.update({
  id: '/api/cron/billing',
  path: '/api/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportPrdRoute = ApiExportPrdRouteImport.update({
  id: '/api/export/prd',
  path: '/api/export/prd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportZipRoute = ApiExportZipRouteImport.update({
  id: '/api/export/zip',
  path: '/api/export/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanPidRoute = ApiKanbanPidRouteImport.update({
  id: '/api/kanban/$pid',
  path: '/api/kanban/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanStreamRoute = ApiKanbanStreamRouteImport.update({
  id: '/api/kanban/stream',
  path: '/api/kanban/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKanbanUpdateStatusRoute = ApiKanbanUpdateStatusRouteImport.update({
  id: '/api/kanban/update-status',
  path: '/api/kanban/update-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateRoute = ApiPaymentsCreateRouteImport.update({
  id: '/api/payments/create',
  path: '/api/payments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskProjectIdRoute = ApiTaskProjectIdRouteImport.update({
  id: '/api/task/$projectId',
  path: '/api/task/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskGenerateRoute = ApiTaskGenerateRouteImport.update({
  id: '/api/task/generate',
  path: '/api/task/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPlanRoute = ApiUserPlanRouteImport.update({
  id: '/api/user/plan',
  path: '/api/user/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdShareTokenRoute = PrdShareTokenRouteImport.update({
  id: '/prd/share/$token',
  path: '/prd/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodebaseProjectIdSessionRoute =
  ApiCodebaseProjectIdSessionRouteImport.update({
    id: '/api/codebase/$projectId/session',
    path: '/api/codebase/$projectId/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodebaseProjectIdStatusRoute =
  ApiCodebaseProjectIdStatusRouteImport.update({
    id: '/api/codebase/$projectId/status',
    path: '/api/codebase/$projectId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsIdLastRouteRoute = ApiProjectsIdLastRouteRouteImport.update({
  id: '/last-route',
  path: '/last-route',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdResetProgressRoute =
  ApiProjectsIdResetProgressRouteImport.update({
    id: '/reset-progress',
    path: '/reset-progress',
    getParentRoute: () => ApiProjectsIdRoute,
  } as any)
const ApiProjectsIdStepRoute = ApiProjectsIdStepRouteImport.update({
  id: '/step',
  path: '/step',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiProjectsIdVersionsRoute = ApiProjectsIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => ApiProjectsIdRoute,
} as any)
const ApiSettingsApiKeysIndexRoute = ApiSettingsApiKeysIndexRouteImport.update({
  id: '/api/settings/api-keys/',
  path: '/api/settings/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApiKeysIdRoute = ApiSettingsApiKeysIdRouteImport.update({
  id: '/api/settings/api-keys/$id',
  path: '/api/settings/api-keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApiKeysAutoRoute = ApiSettingsApiKeysAutoRouteImport.update({
  id: '/api/settings/api-keys/auto',
  path: '/api/settings/api-keys/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsIdRoute = ApiV1ProjectsIdRouteImport.update({
  id: '/api/v1/projects/$id',
  path: '/api/v1/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsIdAcRoute = ApiV1ProjectsIdAcRouteImport.update({
  id: '/ac',
  path: '/ac',
  getParentRoute: () => ApiV1ProjectsIdRoute,
} as any)
const ApiV1ProjectsIdKanbanRoute = ApiV1ProjectsIdKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => ApiV1ProjectsIdRoute,
} as any)
const ApiV1ProjectsIdPrdRoute = ApiV1ProjectsIdPrdRouteImport.update({
  id: '/prd',
  path: '/prd',
  getParentRoute: () => ApiV1ProjectsIdRoute,
} as any)
const ApiV1ProjectsIdTasksRoute = ApiV1ProjectsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ApiV1ProjectsIdRoute,
} as any)
const ApiV1SubtasksIdStatusRoute = ApiV1SubtasksIdStatusRouteImport.update({
  id: '/api/v1/subtasks/$id/status',
  path: '/api/v1/subtasks/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TasksIdStatusRoute = ApiV1TasksIdStatusRouteImport.update({
  id: '/api/v1/tasks/$id/status',
  path: '/api/v1/tasks/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsIdCodebaseAnalysisRoute =
  ApiV1ProjectsIdCodebaseAnalysisRouteImport.update({
    id: '/codebase/analysis',
    path: '/codebase/analysis',
    getParentRoute: () => ApiV1ProjectsIdRoute,
  } as any)
const ApiV1ProjectsIdCodebaseCompleteRoute =
  ApiV1ProjectsIdCodebaseCompleteRouteImport.update({
    id: '/codebase/complete',
    path: '/codebase/complete',
    getParentRoute: () => ApiV1ProjectsIdRoute,
  } as any)
const ApiV1ProjectsIdCodebaseFilesRoute =
  ApiV1ProjectsIdCodebaseFilesRouteImport.update({
    id: '/codebase/files',
    path: '/codebase/files',
    getParentRoute: () => ApiV1ProjectsIdRoute,
  } as any)
const ApiV1ProjectsIdCodebaseManifestRoute =
  ApiV1ProjectsIdCodebaseManifestRouteImport.update({
    id: '/codebase/manifest',
    path: '/codebase/manifest',
    getParentRoute: () => ApiV1ProjectsIdRoute,
  } as any)
const ApiV1ProjectsIdCodebaseSyncRoute =
  ApiV1ProjectsIdCodebaseSyncRouteImport.update({
    id: '/codebase/sync',
    path: '/codebase/sync',
    getParentRoute: () => ApiV1ProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ac/$id': typeof AcIdRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/report-error': typeof ApiReportErrorRoute
  '/ask/$id': typeof AskIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/codebase/$id': typeof CodebaseIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/kanban/$id': typeof KanbanIdRoute
  '/prd/$id': typeof PrdIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/task/$id': typeof TaskIdRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/ac/generate': typeof ApiAcGenerateRoute
  '/api/ac/save': typeof ApiAcSaveRoute
  '/api/ask/options': typeof ApiAskOptionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/export/prd': typeof ApiExportPrdRoute
  '/api/export/zip': typeof ApiExportZipRoute
  '/api/kanban/$pid': typeof ApiKanbanPidRoute
  '/api/kanban/stream': typeof ApiKanbanStreamRoute
  '/api/kanban/update-status': typeof ApiKanbanUpdateStatusRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/task/$projectId': typeof ApiTaskProjectIdRoute
  '/api/task/generate': typeof ApiTaskGenerateRoute
  '/api/user/plan': typeof ApiUserPlanRoute
  '/prd/share/$token': typeof PrdShareTokenRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/codebase/$projectId/session': typeof ApiCodebaseProjectIdSessionRoute
  '/api/codebase/$projectId/status': typeof ApiCodebaseProjectIdStatusRoute
  '/api/projects/$id/last-route': typeof ApiProjectsIdLastRouteRoute
  '/api/projects/$id/reset-progress': typeof ApiProjectsIdResetProgressRoute
  '/api/projects/$id/step': typeof ApiProjectsIdStepRoute
  '/api/projects/$id/versions': typeof ApiProjectsIdVersionsRoute
  '/api/settings/api-keys/$id': typeof ApiSettingsApiKeysIdRoute
  '/api/settings/api-keys/auto': typeof ApiSettingsApiKeysAutoRoute
  '/api/v1/projects/$id': typeof ApiV1ProjectsIdRouteWithChildren
  '/api/settings/api-keys/': typeof ApiSettingsApiKeysIndexRoute
  '/api/v1/projects/$id/ac': typeof ApiV1ProjectsIdAcRoute
  '/api/v1/projects/$id/kanban': typeof ApiV1ProjectsIdKanbanRoute
  '/api/v1/projects/$id/prd': typeof ApiV1ProjectsIdPrdRoute
  '/api/v1/projects/$id/tasks': typeof ApiV1ProjectsIdTasksRoute
  '/api/v1/subtasks/$id/status': typeof ApiV1SubtasksIdStatusRoute
  '/api/v1/tasks/$id/status': typeof ApiV1TasksIdStatusRoute
  '/api/v1/projects/$id/codebase/analysis': typeof ApiV1ProjectsIdCodebaseAnalysisRoute
  '/api/v1/projects/$id/codebase/complete': typeof ApiV1ProjectsIdCodebaseCompleteRoute
  '/api/v1/projects/$id/codebase/files': typeof ApiV1ProjectsIdCodebaseFilesRoute
  '/api/v1/projects/$id/codebase/manifest': typeof ApiV1ProjectsIdCodebaseManifestRoute
  '/api/v1/projects/$id/codebase/sync': typeof ApiV1ProjectsIdCodebaseSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/ac/$id': typeof AcIdRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/report-error': typeof ApiReportErrorRoute
  '/ask/$id': typeof AskIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/codebase/$id': typeof CodebaseIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/kanban/$id': typeof KanbanIdRoute
  '/prd/$id': typeof PrdIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/task/$id': typeof TaskIdRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/ac/generate': typeof ApiAcGenerateRoute
  '/api/ac/save': typeof ApiAcSaveRoute
  '/api/ask/options': typeof ApiAskOptionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/export/prd': typeof ApiExportPrdRoute
  '/api/export/zip': typeof ApiExportZipRoute
  '/api/kanban/$pid': typeof ApiKanbanPidRoute
  '/api/kanban/stream': typeof ApiKanbanStreamRoute
  '/api/kanban/update-status': typeof ApiKanbanUpdateStatusRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/task/$projectId': typeof ApiTaskProjectIdRoute
  '/api/task/generate': typeof ApiTaskGenerateRoute
  '/api/user/plan': typeof ApiUserPlanRoute
  '/prd/share/$token': typeof PrdShareTokenRoute
  '/api/projects': typeof ApiProjectsIndexRoute
  '/api/codebase/$projectId/session': typeof ApiCodebaseProjectIdSessionRoute
  '/api/codebase/$projectId/status': typeof ApiCodebaseProjectIdStatusRoute
  '/api/projects/$id/last-route': typeof ApiProjectsIdLastRouteRoute
  '/api/projects/$id/reset-progress': typeof ApiProjectsIdResetProgressRoute
  '/api/projects/$id/step': typeof ApiProjectsIdStepRoute
  '/api/projects/$id/versions': typeof ApiProjectsIdVersionsRoute
  '/api/settings/api-keys/$id': typeof ApiSettingsApiKeysIdRoute
  '/api/settings/api-keys/auto': typeof ApiSettingsApiKeysAutoRoute
  '/api/v1/projects/$id': typeof ApiV1ProjectsIdRouteWithChildren
  '/api/settings/api-keys': typeof ApiSettingsApiKeysIndexRoute
  '/api/v1/projects/$id/ac': typeof ApiV1ProjectsIdAcRoute
  '/api/v1/projects/$id/kanban': typeof ApiV1ProjectsIdKanbanRoute
  '/api/v1/projects/$id/prd': typeof ApiV1ProjectsIdPrdRoute
  '/api/v1/projects/$id/tasks': typeof ApiV1ProjectsIdTasksRoute
  '/api/v1/subtasks/$id/status': typeof ApiV1SubtasksIdStatusRoute
  '/api/v1/tasks/$id/status': typeof ApiV1TasksIdStatusRoute
  '/api/v1/projects/$id/codebase/analysis': typeof ApiV1ProjectsIdCodebaseAnalysisRoute
  '/api/v1/projects/$id/codebase/complete': typeof ApiV1ProjectsIdCodebaseCompleteRoute
  '/api/v1/projects/$id/codebase/files': typeof ApiV1ProjectsIdCodebaseFilesRoute
  '/api/v1/projects/$id/codebase/manifest': typeof ApiV1ProjectsIdCodebaseManifestRoute
  '/api/v1/projects/$id/codebase/sync': typeof ApiV1ProjectsIdCodebaseSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ac/$id': typeof AcIdRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/report-error': typeof ApiReportErrorRoute
  '/ask/$id': typeof AskIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/codebase/$id': typeof CodebaseIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/kanban/$id': typeof KanbanIdRoute
  '/prd/$id': typeof PrdIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/task/$id': typeof TaskIdRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/ac/generate': typeof ApiAcGenerateRoute
  '/api/ac/save': typeof ApiAcSaveRoute
  '/api/ask/options': typeof ApiAskOptionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/export/prd': typeof ApiExportPrdRoute
  '/api/export/zip': typeof ApiExportZipRoute
  '/api/kanban/$pid': typeof ApiKanbanPidRoute
  '/api/kanban/stream': typeof ApiKanbanStreamRoute
  '/api/kanban/update-status': typeof ApiKanbanUpdateStatusRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/projects/$id': typeof ApiProjectsIdRouteWithChildren
  '/api/task/$projectId': typeof ApiTaskProjectIdRoute
  '/api/task/generate': typeof ApiTaskGenerateRoute
  '/api/user/plan': typeof ApiUserPlanRoute
  '/prd/share/$token': typeof PrdShareTokenRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
  '/api/codebase/$projectId/session': typeof ApiCodebaseProjectIdSessionRoute
  '/api/codebase/$projectId/status': typeof ApiCodebaseProjectIdStatusRoute
  '/api/projects/$id/last-route': typeof ApiProjectsIdLastRouteRoute
  '/api/projects/$id/reset-progress': typeof ApiProjectsIdResetProgressRoute
  '/api/projects/$id/step': typeof ApiProjectsIdStepRoute
  '/api/projects/$id/versions': typeof ApiProjectsIdVersionsRoute
  '/api/settings/api-keys/$id': typeof ApiSettingsApiKeysIdRoute
  '/api/settings/api-keys/auto': typeof ApiSettingsApiKeysAutoRoute
  '/api/v1/projects/$id': typeof ApiV1ProjectsIdRouteWithChildren
  '/api/settings/api-keys/': typeof ApiSettingsApiKeysIndexRoute
  '/api/v1/projects/$id/ac': typeof ApiV1ProjectsIdAcRoute
  '/api/v1/projects/$id/kanban': typeof ApiV1ProjectsIdKanbanRoute
  '/api/v1/projects/$id/prd': typeof ApiV1ProjectsIdPrdRoute
  '/api/v1/projects/$id/tasks': typeof ApiV1ProjectsIdTasksRoute
  '/api/v1/subtasks/$id/status': typeof ApiV1SubtasksIdStatusRoute
  '/api/v1/tasks/$id/status': typeof ApiV1TasksIdStatusRoute
  '/api/v1/projects/$id/codebase/analysis': typeof ApiV1ProjectsIdCodebaseAnalysisRoute
  '/api/v1/projects/$id/codebase/complete': typeof ApiV1ProjectsIdCodebaseCompleteRoute
  '/api/v1/projects/$id/codebase/files': typeof ApiV1ProjectsIdCodebaseFilesRoute
  '/api/v1/projects/$id/codebase/manifest': typeof ApiV1ProjectsIdCodebaseManifestRoute
  '/api/v1/projects/$id/codebase/sync': typeof ApiV1ProjectsIdCodebaseSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/history'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/ac/$id'
    | '/admin/feedback'
    | '/admin/projects'
    | '/admin/transactions'
    | '/admin/users'
    | '/api/chat'
    | '/api/feedback'
    | '/api/report-error'
    | '/ask/$id'
    | '/auth/callback'
    | '/codebase/$id'
    | '/demo/tanstack-query'
    | '/kanban/$id'
    | '/prd/$id'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/feedback'
    | '/settings/notifications'
    | '/settings/profile'
    | '/task/$id'
    | '/admin/'
    | '/settings/'
    | '/api/ac/generate'
    | '/api/ac/save'
    | '/api/ask/options'
    | '/api/auth/$'
    | '/api/cron/billing'
    | '/api/export/prd'
    | '/api/export/zip'
    | '/api/kanban/$pid'
    | '/api/kanban/stream'
    | '/api/kanban/update-status'
    | '/api/payments/create'
    | '/api/payments/webhook'
    | '/api/projects/$id'
    | '/api/task/$projectId'
    | '/api/task/generate'
    | '/api/user/plan'
    | '/prd/share/$token'
    | '/api/projects/'
    | '/api/codebase/$projectId/session'
    | '/api/codebase/$projectId/status'
    | '/api/projects/$id/last-route'
    | '/api/projects/$id/reset-progress'
    | '/api/projects/$id/step'
    | '/api/projects/$id/versions'
    | '/api/settings/api-keys/$id'
    | '/api/settings/api-keys/auto'
    | '/api/v1/projects/$id'
    | '/api/settings/api-keys/'
    | '/api/v1/projects/$id/ac'
    | '/api/v1/projects/$id/kanban'
    | '/api/v1/projects/$id/prd'
    | '/api/v1/projects/$id/tasks'
    | '/api/v1/subtasks/$id/status'
    | '/api/v1/tasks/$id/status'
    | '/api/v1/projects/$id/codebase/analysis'
    | '/api/v1/projects/$id/codebase/complete'
    | '/api/v1/projects/$id/codebase/files'
    | '/api/v1/projects/$id/codebase/manifest'
    | '/api/v1/projects/$id/codebase/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/history'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/pricing'
    | '/ac/$id'
    | '/admin/feedback'
    | '/admin/projects'
    | '/admin/transactions'
    | '/admin/users'
    | '/api/chat'
    | '/api/feedback'
    | '/api/report-error'
    | '/ask/$id'
    | '/auth/callback'
    | '/codebase/$id'
    | '/demo/tanstack-query'
    | '/kanban/$id'
    | '/prd/$id'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/feedback'
    | '/settings/notifications'
    | '/settings/profile'
    | '/task/$id'
    | '/admin'
    | '/settings'
    | '/api/ac/generate'
    | '/api/ac/save'
    | '/api/ask/options'
    | '/api/auth/$'
    | '/api/cron/billing'
    | '/api/export/prd'
    | '/api/export/zip'
    | '/api/kanban/$pid'
    | '/api/kanban/stream'
    | '/api/kanban/update-status'
    | '/api/payments/create'
    | '/api/payments/webhook'
    | '/api/projects/$id'
    | '/api/task/$projectId'
    | '/api/task/generate'
    | '/api/user/plan'
    | '/prd/share/$token'
    | '/api/projects'
    | '/api/codebase/$projectId/session'
    | '/api/codebase/$projectId/status'
    | '/api/projects/$id/last-route'
    | '/api/projects/$id/reset-progress'
    | '/api/projects/$id/step'
    | '/api/projects/$id/versions'
    | '/api/settings/api-keys/$id'
    | '/api/settings/api-keys/auto'
    | '/api/v1/projects/$id'
    | '/api/settings/api-keys'
    | '/api/v1/projects/$id/ac'
    | '/api/v1/projects/$id/kanban'
    | '/api/v1/projects/$id/prd'
    | '/api/v1/projects/$id/tasks'
    | '/api/v1/subtasks/$id/status'
    | '/api/v1/tasks/$id/status'
    | '/api/v1/projects/$id/codebase/analysis'
    | '/api/v1/projects/$id/codebase/complete'
    | '/api/v1/projects/$id/codebase/files'
    | '/api/v1/projects/$id/codebase/manifest'
    | '/api/v1/projects/$id/codebase/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/faq'
    | '/history'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/ac/$id'
    | '/admin/feedback'
    | '/admin/projects'
    | '/admin/transactions'
    | '/admin/users'
    | '/api/chat'
    | '/api/feedback'
    | '/api/report-error'
    | '/ask/$id'
    | '/auth/callback'
    | '/codebase/$id'
    | '/demo/tanstack-query'
    | '/kanban/$id'
    | '/prd/$id'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/feedback'
    | '/settings/notifications'
    | '/settings/profile'
    | '/task/$id'
    | '/admin/'
    | '/settings/'
    | '/api/ac/generate'
    | '/api/ac/save'
    | '/api/ask/options'
    | '/api/auth/$'
    | '/api/cron/billing'
    | '/api/export/prd'
    | '/api/export/zip'
    | '/api/kanban/$pid'
    | '/api/kanban/stream'
    | '/api/kanban/update-status'
    | '/api/payments/create'
    | '/api/payments/webhook'
    | '/api/projects/$id'
    | '/api/task/$projectId'
    | '/api/task/generate'
    | '/api/user/plan'
    | '/prd/share/$token'
    | '/api/projects/'
    | '/api/codebase/$projectId/session'
    | '/api/codebase/$projectId/status'
    | '/api/projects/$id/last-route'
    | '/api/projects/$id/reset-progress'
    | '/api/projects/$id/step'
    | '/api/projects/$id/versions'
    | '/api/settings/api-keys/$id'
    | '/api/settings/api-keys/auto'
    | '/api/v1/projects/$id'
    | '/api/settings/api-keys/'
    | '/api/v1/projects/$id/ac'
    | '/api/v1/projects/$id/kanban'
    | '/api/v1/projects/$id/prd'
    | '/api/v1/projects/$id/tasks'
    | '/api/v1/subtasks/$id/status'
    | '/api/v1/tasks/$id/status'
    | '/api/v1/projects/$id/codebase/analysis'
    | '/api/v1/projects/$id/codebase/complete'
    | '/api/v1/projects/$id/codebase/files'
    | '/api/v1/projects/$id/codebase/manifest'
    | '/api/v1/projects/$id/codebase/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  FaqRoute: typeof FaqRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AcIdRoute: typeof AcIdRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiReportErrorRoute: typeof ApiReportErrorRoute
  AskIdRoute: typeof AskIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CodebaseIdRoute: typeof CodebaseIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  KanbanIdRoute: typeof KanbanIdRoute
  PrdIdRoute: typeof PrdIdRoute
  TaskIdRoute: typeof TaskIdRoute
  ApiAcGenerateRoute: typeof ApiAcGenerateRoute
  ApiAcSaveRoute: typeof ApiAcSaveRoute
  ApiAskOptionsRoute: typeof ApiAskOptionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronBillingRoute: typeof ApiCronBillingRoute
  ApiExportPrdRoute: typeof ApiExportPrdRoute
  ApiExportZipRoute: typeof ApiExportZipRoute
  ApiKanbanPidRoute: typeof ApiKanbanPidRoute
  ApiKanbanStreamRoute: typeof ApiKanbanStreamRoute
  ApiKanbanUpdateStatusRoute: typeof ApiKanbanUpdateStatusRoute
  ApiPaymentsCreateRoute: typeof ApiPaymentsCreateRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiProjectsIdRoute: typeof ApiProjectsIdRouteWithChildren
  ApiTaskProjectIdRoute: typeof ApiTaskProjectIdRoute
  ApiTaskGenerateRoute: typeof ApiTaskGenerateRoute
  ApiUserPlanRoute: typeof ApiUserPlanRoute
  PrdShareTokenRoute: typeof PrdShareTokenRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
  ApiCodebaseProjectIdSessionRoute: typeof ApiCodebaseProjectIdSessionRoute
  ApiCodebaseProjectIdStatusRoute: typeof ApiCodebaseProjectIdStatusRoute
  ApiSettingsApiKeysIdRoute: typeof ApiSettingsApiKeysIdRoute
  ApiSettingsApiKeysAutoRoute: typeof ApiSettingsApiKeysAutoRoute
  ApiV1ProjectsIdRoute: typeof ApiV1ProjectsIdRouteWithChildren
  ApiSettingsApiKeysIndexRoute: typeof ApiSettingsApiKeysIndexRoute
  ApiV1SubtasksIdStatusRoute: typeof ApiV1SubtasksIdStatusRoute
  ApiV1TasksIdStatusRoute: typeof ApiV1TasksIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac/$id': {
      id: '/ac/$id'
      path: '/ac/$id'
      fullPath: '/ac/$id'
      preLoaderRoute: typeof AcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-error': {
      id: '/api/report-error'
      path: '/api/report-error'
      fullPath: '/api/report-error'
      preLoaderRoute: typeof ApiReportErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$id': {
      id: '/ask/$id'
      path: '/ask/$id'
      fullPath: '/ask/$id'
      preLoaderRoute: typeof AskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase/$id': {
      id: '/codebase/$id'
      path: '/codebase/$id'
      fullPath: '/codebase/$id'
      preLoaderRoute: typeof CodebaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban/$id': {
      id: '/kanban/$id'
      path: '/kanban/$id'
      fullPath: '/kanban/$id'
      preLoaderRoute: typeof KanbanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd/$id': {
      id: '/prd/$id'
      path: '/prd/$id'
      fullPath: '/prd/$id'
      preLoaderRoute: typeof PrdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/feedback': {
      id: '/settings/feedback'
      path: '/feedback'
      fullPath: '/settings/feedback'
      preLoaderRoute: typeof SettingsFeedbackRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/task/$id': {
      id: '/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof TaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ac/generate': {
      id: '/api/ac/generate'
      path: '/api/ac/generate'
      fullPath: '/api/ac/generate'
      preLoaderRoute: typeof ApiAcGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ac/save': {
      id: '/api/ac/save'
      path: '/api/ac/save'
      fullPath: '/api/ac/save'
      preLoaderRoute: typeof ApiAcSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask/options': {
      id: '/api/ask/options'
      path: '/api/ask/options'
      fullPath: '/api/ask/options'
      preLoaderRoute: typeof ApiAskOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/billing': {
      id: '/api/cron/billing'
      path: '/api/cron/billing'
      fullPath: '/api/cron/billing'
      preLoaderRoute: typeof ApiCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/prd': {
      id: '/api/export/prd'
      path: '/api/export/prd'
      fullPath: '/api/export/prd'
      preLoaderRoute: typeof ApiExportPrdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/zip': {
      id: '/api/export/zip'
      path: '/api/export/zip'
      fullPath: '/api/export/zip'
      preLoaderRoute: typeof ApiExportZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/$pid': {
      id: '/api/kanban/$pid'
      path: '/api/kanban/$pid'
      fullPath: '/api/kanban/$pid'
      preLoaderRoute: typeof ApiKanbanPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/stream': {
      id: '/api/kanban/stream'
      path: '/api/kanban/stream'
      fullPath: '/api/kanban/stream'
      preLoaderRoute: typeof ApiKanbanStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kanban/update-status': {
      id: '/api/kanban/update-status'
      path: '/api/kanban/update-status'
      fullPath: '/api/kanban/update-status'
      preLoaderRoute: typeof ApiKanbanUpdateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create': {
      id: '/api/payments/create'
      path: '/api/payments/create'
      fullPath: '/api/payments/create'
      preLoaderRoute: typeof ApiPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task/$projectId': {
      id: '/api/task/$projectId'
      path: '/api/task/$projectId'
      fullPath: '/api/task/$projectId'
      preLoaderRoute: typeof ApiTaskProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task/generate': {
      id: '/api/task/generate'
      path: '/api/task/generate'
      fullPath: '/api/task/generate'
      preLoaderRoute: typeof ApiTaskGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/plan': {
      id: '/api/user/plan'
      path: '/api/user/plan'
      fullPath: '/api/user/plan'
      preLoaderRoute: typeof ApiUserPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd/share/$token': {
      id: '/prd/share/$token'
      path: '/prd/share/$token'
      fullPath: '/prd/share/$token'
      preLoaderRoute: typeof PrdShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codebase/$projectId/session': {
      id: '/api/codebase/$projectId/session'
      path: '/api/codebase/$projectId/session'
      fullPath: '/api/codebase/$projectId/session'
      preLoaderRoute: typeof ApiCodebaseProjectIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codebase/$projectId/status': {
      id: '/api/codebase/$projectId/status'
      path: '/api/codebase/$projectId/status'
      fullPath: '/api/codebase/$projectId/status'
      preLoaderRoute: typeof ApiCodebaseProjectIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id/last-route': {
      id: '/api/projects/$id/last-route'
      path: '/last-route'
      fullPath: '/api/projects/$id/last-route'
      preLoaderRoute: typeof ApiProjectsIdLastRouteRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/reset-progress': {
      id: '/api/projects/$id/reset-progress'
      path: '/reset-progress'
      fullPath: '/api/projects/$id/reset-progress'
      preLoaderRoute: typeof ApiProjectsIdResetProgressRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/step': {
      id: '/api/projects/$id/step'
      path: '/step'
      fullPath: '/api/projects/$id/step'
      preLoaderRoute: typeof ApiProjectsIdStepRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/projects/$id/versions': {
      id: '/api/projects/$id/versions'
      path: '/versions'
      fullPath: '/api/projects/$id/versions'
      preLoaderRoute: typeof ApiProjectsIdVersionsRouteImport
      parentRoute: typeof ApiProjectsIdRoute
    }
    '/api/settings/api-keys/': {
      id: '/api/settings/api-keys/'
      path: '/api/settings/api-keys'
      fullPath: '/api/settings/api-keys/'
      preLoaderRoute: typeof ApiSettingsApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/api-keys/$id': {
      id: '/api/settings/api-keys/$id'
      path: '/api/settings/api-keys/$id'
      fullPath: '/api/settings/api-keys/$id'
      preLoaderRoute: typeof ApiSettingsApiKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/api-keys/auto': {
      id: '/api/settings/api-keys/auto'
      path: '/api/settings/api-keys/auto'
      fullPath: '/api/settings/api-keys/auto'
      preLoaderRoute: typeof ApiSettingsApiKeysAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$id': {
      id: '/api/v1/projects/$id'
      path: '/api/v1/projects/$id'
      fullPath: '/api/v1/projects/$id'
      preLoaderRoute: typeof ApiV1ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$id/ac': {
      id: '/api/v1/projects/$id/ac'
      path: '/ac'
      fullPath: '/api/v1/projects/$id/ac'
      preLoaderRoute: typeof ApiV1ProjectsIdAcRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/kanban': {
      id: '/api/v1/projects/$id/kanban'
      path: '/kanban'
      fullPath: '/api/v1/projects/$id/kanban'
      preLoaderRoute: typeof ApiV1ProjectsIdKanbanRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/prd': {
      id: '/api/v1/projects/$id/prd'
      path: '/prd'
      fullPath: '/api/v1/projects/$id/prd'
      preLoaderRoute: typeof ApiV1ProjectsIdPrdRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/tasks': {
      id: '/api/v1/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/api/v1/projects/$id/tasks'
      preLoaderRoute: typeof ApiV1ProjectsIdTasksRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/subtasks/$id/status': {
      id: '/api/v1/subtasks/$id/status'
      path: '/api/v1/subtasks/$id/status'
      fullPath: '/api/v1/subtasks/$id/status'
      preLoaderRoute: typeof ApiV1SubtasksIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tasks/$id/status': {
      id: '/api/v1/tasks/$id/status'
      path: '/api/v1/tasks/$id/status'
      fullPath: '/api/v1/tasks/$id/status'
      preLoaderRoute: typeof ApiV1TasksIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$id/codebase/analysis': {
      id: '/api/v1/projects/$id/codebase/analysis'
      path: '/codebase/analysis'
      fullPath: '/api/v1/projects/$id/codebase/analysis'
      preLoaderRoute: typeof ApiV1ProjectsIdCodebaseAnalysisRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/codebase/complete': {
      id: '/api/v1/projects/$id/codebase/complete'
      path: '/codebase/complete'
      fullPath: '/api/v1/projects/$id/codebase/complete'
      preLoaderRoute: typeof ApiV1ProjectsIdCodebaseCompleteRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/codebase/files': {
      id: '/api/v1/projects/$id/codebase/files'
      path: '/codebase/files'
      fullPath: '/api/v1/projects/$id/codebase/files'
      preLoaderRoute: typeof ApiV1ProjectsIdCodebaseFilesRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/codebase/manifest': {
      id: '/api/v1/projects/$id/codebase/manifest'
      path: '/codebase/manifest'
      fullPath: '/api/v1/projects/$id/codebase/manifest'
      preLoaderRoute: typeof ApiV1ProjectsIdCodebaseManifestRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
    '/api/v1/projects/$id/codebase/sync': {
      id: '/api/v1/projects/$id/codebase/sync'
      path: '/codebase/sync'
      fullPath: '/api/v1/projects/$id/codebase/sync'
      preLoaderRoute: typeof ApiV1ProjectsIdCodebaseSyncRouteImport
      parentRoute: typeof ApiV1ProjectsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsFeedbackRoute: typeof SettingsFeedbackRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsFeedbackRoute: SettingsFeedbackRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiProjectsIdRouteChildren {
  ApiProjectsIdLastRouteRoute: typeof ApiProjectsIdLastRouteRoute
  ApiProjectsIdResetProgressRoute: typeof ApiProjectsIdResetProgressRoute
  ApiProjectsIdStepRoute: typeof ApiProjectsIdStepRoute
  ApiProjectsIdVersionsRoute: typeof ApiProjectsIdVersionsRoute
}

const ApiProjectsIdRouteChildren: ApiProjectsIdRouteChildren = {
  ApiProjectsIdLastRouteRoute: ApiProjectsIdLastRouteRoute,
  ApiProjectsIdResetProgressRoute: ApiProjectsIdResetProgressRoute,
  ApiProjectsIdStepRoute: ApiProjectsIdStepRoute,
  ApiProjectsIdVersionsRoute: ApiProjectsIdVersionsRoute,
}

const ApiProjectsIdRouteWithChildren = ApiProjectsIdRoute._addFileChildren(
  ApiProjectsIdRouteChildren,
)

interface ApiV1ProjectsIdRouteChildren {
  ApiV1ProjectsIdAcRoute: typeof ApiV1ProjectsIdAcRoute
  ApiV1ProjectsIdKanbanRoute: typeof ApiV1ProjectsIdKanbanRoute
  ApiV1ProjectsIdPrdRoute: typeof ApiV1ProjectsIdPrdRoute
  ApiV1ProjectsIdTasksRoute: typeof ApiV1ProjectsIdTasksRoute
  ApiV1ProjectsIdCodebaseAnalysisRoute: typeof ApiV1ProjectsIdCodebaseAnalysisRoute
  ApiV1ProjectsIdCodebaseCompleteRoute: typeof ApiV1ProjectsIdCodebaseCompleteRoute
  ApiV1ProjectsIdCodebaseFilesRoute: typeof ApiV1ProjectsIdCodebaseFilesRoute
  ApiV1ProjectsIdCodebaseManifestRoute: typeof ApiV1ProjectsIdCodebaseManifestRoute
  ApiV1ProjectsIdCodebaseSyncRoute: typeof ApiV1ProjectsIdCodebaseSyncRoute
}

const ApiV1ProjectsIdRouteChildren: ApiV1ProjectsIdRouteChildren = {
  ApiV1ProjectsIdAcRoute: ApiV1ProjectsIdAcRoute,
  ApiV1ProjectsIdKanbanRoute: ApiV1ProjectsIdKanbanRoute,
  ApiV1ProjectsIdPrdRoute: ApiV1ProjectsIdPrdRoute,
  ApiV1ProjectsIdTasksRoute: ApiV1ProjectsIdTasksRoute,
  ApiV1ProjectsIdCodebaseAnalysisRoute: ApiV1ProjectsIdCodebaseAnalysisRoute,
  ApiV1ProjectsIdCodebaseCompleteRoute: ApiV1ProjectsIdCodebaseCompleteRoute,
  ApiV1ProjectsIdCodebaseFilesRoute: ApiV1ProjectsIdCodebaseFilesRoute,
  ApiV1ProjectsIdCodebaseManifestRoute: ApiV1ProjectsIdCodebaseManifestRoute,
  ApiV1ProjectsIdCodebaseSyncRoute: ApiV1ProjectsIdCodebaseSyncRoute,
}

const ApiV1ProjectsIdRouteWithChildren = ApiV1ProjectsIdRoute._addFileChildren(
  ApiV1ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  FaqRoute: FaqRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AcIdRoute: AcIdRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiReportErrorRoute: ApiReportErrorRoute,
  AskIdRoute: AskIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CodebaseIdRoute: CodebaseIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  KanbanIdRoute: KanbanIdRoute,
  PrdIdRoute: PrdIdRoute,
  TaskIdRoute: TaskIdRoute,
  ApiAcGenerateRoute: ApiAcGenerateRoute,
  ApiAcSaveRoute: ApiAcSaveRoute,
  ApiAskOptionsRoute: ApiAskOptionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronBillingRoute: ApiCronBillingRoute,
  ApiExportPrdRoute: ApiExportPrdRoute,
  ApiExportZipRoute: ApiExportZipRoute,
  ApiKanbanPidRoute: ApiKanbanPidRoute,
  ApiKanbanStreamRoute: ApiKanbanStreamRoute,
  ApiKanbanUpdateStatusRoute: ApiKanbanUpdateStatusRoute,
  ApiPaymentsCreateRoute: ApiPaymentsCreateRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiProjectsIdRoute: ApiProjectsIdRouteWithChildren,
  ApiTaskProjectIdRoute: ApiTaskProjectIdRoute,
  ApiTaskGenerateRoute: ApiTaskGenerateRoute,
  ApiUserPlanRoute: ApiUserPlanRoute,
  PrdShareTokenRoute: PrdShareTokenRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
  ApiCodebaseProjectIdSessionRoute: ApiCodebaseProjectIdSessionRoute,
  ApiCodebaseProjectIdStatusRoute: ApiCodebaseProjectIdStatusRoute,
  ApiSettingsApiKeysIdRoute: ApiSettingsApiKeysIdRoute,
  ApiSettingsApiKeysAutoRoute: ApiSettingsApiKeysAutoRoute,
  ApiV1ProjectsIdRoute: ApiV1ProjectsIdRouteWithChildren,
  ApiSettingsApiKeysIndexRoute: ApiSettingsApiKeysIndexRoute,
  ApiV1SubtasksIdStatusRoute: ApiV1SubtasksIdStatusRoute,
  ApiV1TasksIdStatusRoute: ApiV1TasksIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
